linters:
    Comment:
        enabled: true
        allowed: ""

    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space
        width: 4

    IdSelector:
        enabled: false

    ColorVariable:
        enabled: false

    SelectorDepth:
        max_depth: 5

    NestingDepth:
        max_depth: 5

    LeadingZero:
        enabled: false
